# Conclusions, Contributions, and Future Work

see Jacek's thesis

## Research Summary

## Summary of Results

## Methodology

## Contributions

From ASIST award session

FOLLOW UP WITH ...

- Change of the self, self-reflection
- Look at anthropology perspective

ROB:

- Look at qualitative data. More interesting

HEATHER:

- what can we share back to the teachers of the course, librarians and others


## Limitations

- No PDF
- N=16 to N=10
- Also check anticipated limitations section from proposal
- Did not assess goodness of fit of whether first order Markov chain is the most appropriate for modelling search tactic transitions (Besag and Mondal’s (2013) statistical test)
- did not track revisits across different tasks

Some difficulties:

- opening same URL in 2 different tabs and switching between them for a while before realising one is different from the other
  - or maybe long webpage (e.g.) book - two tabs at two different locations in webpage

## Future Work

- Bing + ChatGPT, from MSR blogpost:
  - https://blogs.microsoft.com/blog/2023/02/07/reinventing-search-with-a-new-ai-powered-microsoft-bing-and-edge-your-copilot-for-the-web/
- Google + ChatGPT, from Sundar Pichai
  - https://blog.google/technology/ai/bard-google-ai-search-updates/
  - "AI features in Search can distill information to help you see the big picture."

Contrary opinions_
- https://www.newyorker.com/tech/annals-of-technology/chatgpt-is-a-blurry-jpeg-of-the-web
  - "When we’re dealing with sequences of words, lossy compression looks smarter than lossless compression."
  - hallucinations
- https://abcnews4.com/news/nation-world/experts-warn-dangers-ai-google-microsoft-push-new-chatbots-chatgpt-bard-technology-big-tech-open-ended-questions-responses-alphabet-misinformation-disinformation-internet-new-developments-bing-search-engines
  - Matt is here
  - potential to misinformation

Final feedback:
P022Pisa said
> *It is great to be able to participate in the research this semester. Using the extension somehow brings me postive feedback and that helps me in study I303. So I wanna say thank you*
> - P022Pisa


## New references

Be sure to add new references

- https://www.mdpi.com/2673-4001/4/1/8
- https://link.springer.com/article/10.1007/s10648-023-09730-8
- Claudia Hauff's works from CHIIR2020 onwards
- SYR and other's works