# SUR1: Entry Survey {#appendix:signup_survey}

## Demographics {#app:demographics}

1.  Please select the degree level/name of the program you are in.

2.  Please state which year of the program you are in.

3.  Please state your major(s)

4.  Do you have native-level familiarity with English language? Yes / No
    / Other:

5.  Please state your age (in years)

6.  Please state your gender

7.  With which ethnicities do you identify? Please check all that apply:

    -   African

    -   African American / Black

    -   Asian - East

    -   Asian - South East

    -   Asian - South

    -   Asian - Middle East

    -   Caucasian / White

    -   Hispanic / Latinx

    -   Native American

    -   Pacific Islander

    -   Mixed

    -   Other:

8.  Are you an international student? Yes / No; If Yes, where are you
    originally from?

9.  Please enter an email address that you check regularly. We will send
    communications and compensation information to this email address.

10. Your name as you would like us to address you.

## Search and IT Proficiency {#app:search_it_proficiency}

1.  Which device(s) and browser(s) do you normally use to surf the
    internet?

                   Chrome   Safari   Firefox   Edge   Opera   Other   None
      ------------ -------- -------- --------- ------ ------- ------- ------
      Desktop                                                         
      Laptop                                                          
      Tablet                                                          
      Smartphone                                                      

2.  How comfortable are you with using Mozilla Firefox to search
    information on the internet?

    -   I do not know how to use Mozilla Firefox.

    -   I have never used Mozilla Firefox.

    -   I feel very uncomfortable to use Mozilla Firefox.

    -   I feel uncomfortable to use Mozilla Firefox.

    -   I feel neither comfortable nor uncomfortable to use Mozilla
        Firefox.

    -   I feel comfortable to use Mozilla Firefox.

    -   I feel very comfortable to use Mozilla Firefox.

    -   Other:

3.  Which search engines do you normally use?

    -   Google

    -   Bing

    -   Baidu

    -   Yahoo!

    -   Yandex

    -   DuckDuckGo

    -   Other:

 \
The following items are adapted from the Digital Health Literacy
Instrument (DHLI) by [@van2017development].

*On a scale of 1 to 5 ...*

*(1) Very difficult/Very seldom \| Difficult/Seldom \| Neutral \|
Easy/Often \| Very easy/Very often (5)*

*How easy or difficult is it for you to...*

4.  Use the keyboard of a computer (e.g., to type words)?

5.  Use the mouse (e.g., to put the cursor in the right field or to
    click)?

6.  Use the buttons or links and hyperlinks on websites?

*When you search the Internet for information, how easy or difficult is
it for you to ...*

7.  Make a choice from all the information you find?

8.  Use the proper words or search query to find the information you are
    looking for

9.  Find the exact information you are looking for?

10. Decide whether the information is reliable or not?

11. Decide whether the information is written with commercial interests
    (e.g., by people trying to sell a product)?

12. Check different websites to see whether they provide the same
    information?

13. Decide if the information you found is applicable to your situation?

14. Apply the information you found in your daily life?

15. Use the information you found to make decisions about your life

*When you search the Internet for information, how often does it happen
that...*

15. You lose track of where you are on a website or the Internet?

16. You do not know how to return to a previous page?

17. You click on something and get to see something different than you
    expected?

 \
The following items are adapted from the Search Self-Efficacy Scale
(SSE) by [@brennan2016factor].

*On a scale of 1 to 5, how confident are you that you can ...*

*(1) Not at all confident \| Neither confident nor unconfident \|
Totally confident (5)*

18. Identify the major requirements of the search from the initial
    statement of the topic.

19. Correctly develop search queries to reflect my requirements.

20. Use special syntax in advanced searching (e.g., AND, OR, NOT).

21. Evaluate the resulting list to monitor the success of my approach.

22. Develop a search query which will retrieve a large number of
    appropriate articles.

23. Find an adequate number of articles.

24. Find articles similar in quality to those obtained by a professional
    searcher.

25. Devise a query which will result in a very small percentage of
    irrelevant items on my list.

26. Efficiently structure my time to complete the task.

27. Develop a focused search query that will retrieve a small number of
    appropriate articles.

28. Distinguish between relevant and irrelevant articles.

29. Complete the search competently and effectively.

30. Complete the individual steps of the search with little difficulty.

31. Structure my time effectively so that I will finish the search in
    the allocated time.

## Course Load and Other Engagements {#app:course_load}

1.  How many total weekly hours of coursework are you registered for
    this semester?

2.  How many weekly hours do you anticipate putting in for studying this
    course?

3.  What are your other time commitments, as hours per week? (enter 0 if
    not applicable)

    -   jobs

    -   extra-curriculars

    -   other

4.  Do you hold a position of responsibility (officer / committee
    member) in any (student) organisation? Yes / No

## Note-taking Strategies {#app:note_taking_strategies}

Adapted from *Listening and Note Taking Survey* by
[@note_taking_survey_penn_state], and *Note Taking Strategies Inventory*
by [@note_taking_strategies_umass].

*For each question, choose the response that best describes your actions
(not the one that describes what you think you should be doing). There
are no right or wrong answers. In general (not specifically for this
course)*

1.  I take notes using (check all that apply)

    -   Paper and Pen / Pencil

    -   Laptop / Desktop

    -   Tablet with Keyboard

    -   Tablet with Stylus / Digital Pen

2.  When taking notes on the laptop, I minimize distractions by:

3.  Are you familiar with "concept maps"?

    -   Never heard of it

    -   Heard of it, never used it

    -   Used it a few times in the past

    -   Used it quite often in the past; now do not use it

    -   Use it regularly

*On a scale of 1 to 5 ...*

*(1) Never \| Rarely \| Sometimes \| Often \| Always (5)*

4.  I read my assignments before I go to lecture.

5.  I find lectures interesting and/or challenging.

6.  My lecture notes are well organized.

7.  I recognize main ideas in lectures.

8.  I recognize supporting details of main ideas.

9.  I recognize patterns in lectures, e.g., cause-effect,
    concept-example.

10. My lecture notes are complete.

11. I recognize relationships between lecture and readings.

12. I integrate my lecture notes with my reading notes.

13. I summarize my notes, both lecture and reading, in my own words.

14. I review my notes immediately after class.

15. I conduct weekly reviews of my notes.

16. I edit my notes within 24 hours after class.

17. I take notes

18. I put dates on my notes

19. I makes notes in the margins of the text when I read (on paper /
    digital medium, e.g. iPad and Apple Pencil)

20. I pause periodically while reviewing notes to summarize or
    paraphrase the information.

21. I use diagrams in my notes

22. I use different colours when writing notes

23. I create outlines, concept maps or organizational charts of how
    ideas fit together.

24. I write down questions I want to ask the instructor

25. I reorganize and fill in notes I took in class

26. I put things in my own words

27. I rewrite my notes

28. I use abbreviations in my notes

29. I write out my own descriptions of the main concepts

30. I keep track of things I do not understand and note when they
    finally become clear and what made that happen

31. I understand my notes

32. I refer back to my notes

```{=html}
<!-- -->
```
33. How do you organise your notes?

34. How often do you refer back to your notes?

35. Have you ever wished that you had written better notes? Yes / No.
    Why?

36. How long do you store your notes for?

    -   Till the end of the semester

    -   End of academic year

    -   End of college

    -   Lifelong

37. How do you search for a bit of information in your notes?

## Motivation {#app:imi}

Adapted from Intrinsic Motivation Inventory (IMI) [@ryan1982control].
Items will be randomly ordered.

*For each of the following statements, please indicate how true it is
for you, using the following scale:*

*(1) not at all true \| somewhat true \| very true (5)*

**Interest/Enjoyment**\
I will enjoy taking this course very much.\
This course will be fun to do.\
I think this will be a boring course. (R)\
This course will not hold my attention at all. (R)\
I would describe this course as very interesting.\
I think this course will be quite enjoyable.

 \
**Perceived Competence**\
I think I will be pretty good at this course.\
I think I will be doing pretty well at this course, compared to other
students.\
After working at this course for awhile, I will feel pretty competent.\
I think I will be satisfied with my performance in this course.\
I think I am pretty skilled at this course.\
This is a course that I think would not be able to do very well. (R)

 \
**Effort/Importance**\
I plan to put a lot of effort into this course.\
I don't think I will try very hard to do well at this course. (R)\
I will try very hard on this course.\
It is important to me to do well in this course.\
I do not plan to put much energy into this course. (R)

 \
**Value/Usefulness** [^1]\
I believe this course could be of some value to me.\
I think that doing this course is useful for learning about\
I think this course is important to take because it can\
I think taking this course could help me to\
I believe taking this course could be beneficial to me.\
I think this is an important course.

 \
**Scoring directions:** Score each response from 1 (not at all true) to
5 (very true). Then reverse score the items marked with (R). To do that,
subtract the item response from 6, and use the resulting number as the
item score. Then, calculate subscale scores by averaging across all of
the items on that subscale. The subscale scores are then used in the
analyses of relevant research questions.

## Self-regulation {#app:srq}

Self-Regulation Questionnaire (SRQ) by [@brown1999self].

*Please answer the following questions by selecting the option that best
describes how you are. There are no right or wrong answers. Work quickly
and don't think too long about your answers.*

*(1) Strongly Disagree \| Disagree \| Neutral \| Agree \| Strongly Agree
(5)*

::: multicols
2

1.  I usually keep track of my progress toward my goals.

2.  My behavior is not that different from other people's. (R)

3.  Others tell me that I keep on with things too long. (R)

4.  I doubt I could change even if I wanted to. (R)

5.  I have trouble making up my mind about things. (R)

6.  I get easily distracted from my plans. (R)

7.  I reward myself for progress toward my goals.

8.  I don't notice the effects of my actions until it's too late. (R)

9.  My behavior is similar to that of my friends. Evaluating

10. It's hard for me to see anything helpful about changing my ways.
    Triggering R

11. I am able to accomplish goals I set for myself. Searching

12. I put off making decisions. Planning R

13. I have so many plans that it's hard for me to focus on any one of
    them. (R)

14. I change the way I do things when I see a problem with how things
    are going.

15. It's hard for me to notice when I've "had enough" (alcohol, food,
    sweets, internet, social media) (R)

16. I think a lot about what other people think of me.

17. I am willing to consider other ways of doing things.

18. If I wanted to change, I am confident that I could do it.

19. When it comes to deciding about a change, I feel overwhelmed by the
    choices. (R)

20. I have trouble following through with things once I've made up my
    mind to do something. (R)

21. I don't seem to learn from my mistakes. (R)

22. I'm usually careful not to overdo it when working, eating, drinking,
    or being on social media.

23. I tend to compare myself with other people.

24. I enjoy a routine, and like things to stay the same. (R)

25. I have sought out advice or information about changing. Searching

26. I can come up with lots of ways to change, but it's hard for me to
    decide which one to use. (R)

27. I can stick to a plan that's working well.

28. I usually only have to make a mistake one time in order to learn
    from it.

29. I don't learn well from punishment. (R)

30. I have personal standards, and try to live up to them.

31. I am set in my ways. (R)

32. As soon as I see a problem or challenge, I start looking for
    possible solutions.

33. I have a hard time setting goals for myself. (R)

34. I have a lot of willpower.

35. When I'm trying to change something, I pay a lot of attention to how
    I'm doing.

36. I usually judge what I'm doing by the consequences of my actions.

37. I don't care if I'm different from most people. (R)

38. As soon as I see things aren't going right I want to do something
    about it.

39. There is usually more than one way to accomplish something.

40. I have trouble making plans to help me reach my goals. (R)

41. I am able to resist temptation.

42. I set goals for myself and keep track of my progress.

43. Most of the time I don't pay attention to what I'm doing. (R)

44. I try to be like people around me.

45. I tend to keep doing the same thing, even when it doesn't work. (R)

46. I can usually find several different possibilities when I want to
    change something.

47. Once I have a goal, I can usually plan how to reach it.

48. I have rules that I stick by no matter what.

49. If I make a resolution to change something, I pay a lot of attention
    to how I'm doing.

50. Often I don't notice what I'm doing until someone calls it to my
    attention. (R)

51. I think a lot about how I'm doing.

52. Usually I see the need to change before others do.

53. I'm good at finding different ways to get what I want.

54. I usually think before I act.

55. Little problems or distractions throw me off course. (R)

56. I feel bad when I don't meet my goals.

57. I learn from my mistakes.

58. I know how I want to be.

59. It bothers me when things aren't the way I want them.

60. I call in others for help when I need it.

61. Before making a decision, I consider what is likely to happen if I
    do one thing or another.

62. I give up quickly. (R)

63. I usually decide to change and hope for the best. (R)
:::

**Scoring Directions:** Score each response from 1 (strongly disagree)
to 5 (strongly agree), and calculate the following subscale scores by
summing the items on that subscale. Items marked (R) are reverse-coded
(i.e. 1 = strongly agree and 5 = strongly disagree).

1.  *Receiving relevant information:* 1, 8, 15, 22, 29, 36, 43, 50, 57

2.  *Evaluating the information and comparing it to norms:* 2, 9, 16,
    23, 30, 37, 44, 51, 58

3.  *Triggering change:* 3, 10, 17, 24, 31, 38, 45, 52, 59

4.  *Searching for options:* 4, 11, 18, 25, 32, 39, 46, 53, 60

5.  *Formulating a plan:* 5, 12, 19, 26, 33, 40, 47, 54, 61

6.  *Implementing the plan:* 6, 13, 20, 27, 34, 41, 48, 55, 62

7.  *Assessing the plan's effectiveness:* 7, 14, 21, 28, 35, 42, 49, 56,
    63

## Metacognition {#app:mai}

Metacognivite Awareness Inventory (MAI) proposed by
[@schraw1994assessing] and revised by [@terlecki2018call].

*Think of yourself as a **learner**. Read each statement carefully, and
rate it as it generally applies to you when you are in the role of a
learner (student, attending classes, university etc.) Please indicate
how true each reason is for you using the following scale:*

::: tabular
\| x0.18 \| x0.18 \| x0.18 \| x0.18 \| x0.18 \| *I **NEVER** do this* &
*I do this **infrequently*** & *I do this **inconsistently*** & *I do
this **frequently*** & *I **ALWAYS** do this*\
:::

::: multicols
2

1.  I ask myself periodically if I am meeting my goals.

2.  I consider several alternatives to a problem before I answer.

3.  I try to use strategies that have worked in the past.

4.  I pace myself while learning in order to have enough time.

5.  I understand my intellectual strengths and weaknesses.

6.  I think about what I really need to learn before I begin a task.

7.  I know how well I did once I finish a test.

8.  I set specific goals before I begin a task.

9.  I slow down when I encounter important information.

10. I know what kind of information is most important to learn.

11. I ask myself if I have considered all options when solving a
    problem.

12. I am good at organizing information.

13. I consciously focus my attention on important information.

14. I have a specific purpose for each strategy I use.

15. I learn best when I know something about the topic.

16. I know what the teacher expects me to learn.

17. I am good at remembering information.

18. I use different learning strategies depending on the situation.

19. I ask myself if there was an easier way to do things after I finish
    a task.

20. I have control over how well I learn.

21. I periodically review to help me understand important relationships.

22. I ask myself questions about the material before I begin.

23. I think of several ways to solve a problem and choose the best one.

24. I summarize what I've learned after I finish.

25. I ask others for help when I don't understand something.

26. I can motivate myself to learn when I need to.

27. I am aware of what strategies I use when I study.

28. I find myself analyzing the usefulness of strategies while I study.

29. I use my intellectual strengths to compensate for my weaknesses.

30. I focus on the meaning and significance of new information.

31. I create my own examples to make information more meaningful.

32. I am a good judge of how well I understand something.

33. I find myself using helpful learning strategies automatically.

34. I find myself pausing regularly to check my comprehension.

35. I know when each strategy I use will be most effective.

36. I ask myself how well I accomplish my goals once I'm finished.

37. I draw pictures or diagrams to help me understand while learning.

38. I ask myself if I have considered all options after I solve a
    problem.

39. I try to translate new information into my own words.

40. I change strategies when I fail to understand.

41. I use the organizational structure of the text to help me learn.

42. I read instructions carefully before I begin a task.

43. I ask myself if what I'm reading is related to what I already know.

44. I reevaluate my assumptions when I get confused.

45. I organize my time to best accomplish my goals.

46. I learn more when I am interested in the topic.

47. I try to break studying down into smaller steps.

48. I focus on overall meaning rather than specifics.

49. I ask myself questions about how well I am doing while I am learning
    something new.

50. I ask myself if I learned as much as I could have once I finish a
    task.

51. I stop and go back over new information that is not clear.

52. I stop and reread when I get confused.
:::

**Scoring Directions:** Score each response from 1 (never) to 5
(always), and calculate the following subscale scores by summing the
items on that subscale.

*Knowledge about Cognition:*

1.  *Declarative Knowledge:* 5, 10, 12, 16, 17, 20, 32, 46 (score out of
    $8\times5 = 40$)

2.  *Procedural Knowledge:* 3, 14, 27, 33 (score out of $4\times5 = 20$)

3.  *Conditional Knowledge:* 15, 18, 26, 29, 35 (score out of
    $5\times5 = 25$)

*Regulation of Cognition:*

1.  *Planning:* 4, 6, 8, 22, 23, 42, 45 (score out of $7\times5 = 35$)

2.  *Information Management Strategies:* 9, 13, 30, 31, 37, 39, 41, 43,
    47, 48 (score out of $10\times5 = 50$)

3.  *Comprehension Monitoring:* 1, 2, 11, 21, 28, 34, 49 (score out of
    $7\times5 = 35$)

4.  *Debugging Strategies:* 25, 40, 44, 51, 52 (score out of
    $5\times5 = 25$)

5.  *Evaluation:* 7, 19, 24, 36, 38, 50 (score out of $6\times5 = 30$)

[^1]: items with blanks will be completed with contextual information
    once the study site is finalised
