# `QSNR`: Questionnaires {#app-qsnr}

## `QSNR0`: Recruitment Questionnaire {#app-qsnr0}


Thank you SO much for your willingness to participate in the LongSAL research study. The aim of this study is to identify how search engines can better support the needs of university students’ learning and education. To be eligible for this study, you must be enrolled in the I 303 Ethical Foundations for Informatics course for the Spring 2022 semester. Please fill out the information requested below. We will get back to you if you are selected to participate in the study. The principal investigator, Nilavra Bhattacharya, can be reached at `<email-address>` for any questions or concerns. 


1. Please select which section of the I-303 Ethical Foundations for Informatics course you are enrolled in.

   - TUE: FLEISCHMANN, VERMA 
   - WED: FLEISCHMANN, GURSOY 
   - THU: FLEISCHMANN, BAUTISTA 
   - FRI: FLEISCHMANN, DAY 


2. Please select the degree level/name of the program you are in.

   - Bachelor's 
   - Master's 
   - Integrated Bachelor's and Master's 
   - PhD 
   - Other .....



3. Please state which year of the program you are in.

   - Freshman 
   - Sophomore 
   - Junior 
   - Senior 
   - Graduate Year 1 
   - Graduate Year 2 
   - Other .....



4. Please state your major(s) .....




5. Do you have native-level familiarity with English language?

   - Yes 
   - No 
   - Other: .....



6. Please state your age (in years) .....



7. Please state your gender .....



8. With which ethnicities do you identify? Please select all that apply:

   - African 
   - African American / Black 
   - Asian - East 
   - Asian - South East 
   - Asian - South 
   - Asian - Middle East 
   - Caucasian / White 
   - Hispanic / Latinx 
   - Native American 
   - Pacific Islander 
   - Mixed 
   - Other .....



9. Are you an international student? If "yes", where are you originally from?

   - Yes .....
   - No 




10. We need your contact information to communicate with you over the semester (if you are selected). Your contact information will not be used in any other way, and will be kept private. Please enter an email address that you check regularly. We will use this email address to send communications and Amazon Gift Cards as payment.
.....



11. Your name as you would like us to address you (solely for communication).
.....








## `QSNR1` - `QSNR3`: Entry, Mid-term and Exit Questionnaires


### Consent Form {#app-qsnr-consent-form}

Consent to Participate in Research
    
**Basic Study Information:**

- UT Austin IRB Approved
- **Submission ID:** STUDY00002136
- **Date Approved:** December 8, 2021
- **Title:** LongSAL: A Longitudinal study on Searching as Learning
- **Principal Investigator:** Nilavra Bhattacharya, PhD Student, School of Information, UT Austin
- **Faculty Advisor:** Jacek Gwizdka, Associate Professor, School of Information, UT Austin



**Invitation to be Part of a Research Study**
Things you should know:

- The purpose of the study is to identify how search engines can be improved to better support university students’ learning and education.
- In order to participate, you must be enrolled in the I303 Ethical Foundations for Informatics course in the Spring 2022 semester.
- If you choose to participate, you will be asked, over the course of the semester, to take three surveys (10-15 mins each), attend two Zoom sessions (60-90 mins each), and record browsing activity while working on Final Project Paper. All parts of the study will be conducted online.
- Risks or discomforts involved in this research study are not greater than everyday life.
- There is no direct benefit for participating in this study.
- Taking part in this research study is voluntary. You do not have to participate, and you can stop at any time.
 
More detailed information may be described later in this form.
 
Please take time to read this entire form and ask questions before deciding whether to take part in this research study.



**What is the study about, and why are we doing it?**
The aim of this longitudinal study is to identify how university students search the web for educational research activities. Findings from this study will help to understand how search engines can be improved to better support university students’ learning and education, and therefore help to build more human-centred and learning-centric search systems.



**What will happen if you take part in this study?**
If you agree to take part in this study, you will be asked to perform the following activities over the duration of the Spring 2022 semester.

<!-- TODO: insert `study-proc-consent-form.jpeg` -->

<!-- A detailed description of each of the tasks are available at https://longsal.ischool.utexas.edu -->



**How long will this study take and how many people will be in the study?**
Participation in this study will take approx. 10-15 minutes each for the three surveys, and 60-90 minutes each for the two synchronous Zoom sessions. There will be about 30-40 participants in total in this study. 



**What risks and discomforts might you experience from being in this study?**
There are no major foreseeable risks to participating in this study. There may be a very minimal potential risk of confidentiality, or possibly frustrations with some tasks. To address the risk of confidentiality, once data collection is completed, all personally identifying data will be destroyed by erasing all digital files and shredding all the physical records. To address the risk of frustration, you can move at your own pace, or stop whenever you wish. 



**How could you benefit from this study?**
You will receive no direct benefit from participating in this study; however, this study will help to improve our current understanding of how students search the web for education and learning-related goals over time. This will the development of better learning-centric search systems. 



**What data will we collect from you?**
As part of this study, we will collect your:

- audio, screen recordings, and browsing logs when you are participating in the Zoom sessions. You can turn off your face video during these sessions.
- browsing log data, when you are performing research for the course final project. You can start and stop the logging when you choose.
- anonymized submissions for the final project at various points in the Semester
- self-reported grades for the final project assignments that you received  

The holistic data about your research-assignment related internet search activity, the material that you produce for your assignments, and the scores you receive for those assignments, will help us understand where students perform well, where things can be improved, and how search engines can be improved to better support university students’ learning and education.



**How will we protect your information?**
We will protect the privacy and the confidentiality of your data by:

- Assigning you a coded username at the beginning of the study to protect confidentiality, and all your submitted data will be linked to this coded username.
- All digital data generated in the study will be stored via a university-approved secure cloud-based storage service and password-protected computers. All computers used in the project are password protected.
- Audio recordings will be listened to only for research purposes. Audio recordings will be transcribed and coded. No information that can be used to uniquely identify an individual will be present  

We may share your data with other researchers for future research studies that may be similar to this study or maybe very different. In these cases, the data shared with other researchers will NOT include any information that can directly identify you.
 
We plan to publish the results of this study. To protect your privacy, we will NOT include any information that could directly identify you.



**What will happen to the information we collect about you after the study is over?**
We will keep your research data to use for future analyses and publications. Any information that can directly identify you will be deleted from the research data collected as part of the project. 



**How will we compensate you for being part of the study?**
You will receive up to USD 150 in Amazon Gift cards if you complete all the components of the study, as described above. If you choose to withdraw early from the study, you will receive compensation for the parts you have completed. You will be responsible for any taxes assessed on the compensation. 



**Your Participation in this Study is Voluntary**
It is totally up to you to decide to be in this research study. Participating in this study is voluntary. Your decision to participate will not affect your relationship with The University of Texas at Austin. You will not lose any benefits or rights you already had if you decide not to participate. Even if you decide to be part of the study now, you may change your mind and stop at any time. You do not have to answer any questions you do not want to answer. 


**This Study is NOT a part of the I 303 Ethical Foundations of Informatics course:**

- The study researchers intend to only recruit participants from the student pool enrolled in the course.
- The course instructors will not share any student data with the researchers.
- The course instructors will not be aware of which students did or did not participate in this study.
- Participation in this study is completely voluntary, and in no way affects the outcome of this course for you, or your academic relations with the course instructors.

Even after consenting to participate, you can choose to withdraw consent anytime during the semester. We will delete all the data collected from you up to that point. You will receive compensation for the parts you have completed, as outlined above. 



**Contact Information for the Study Team and Questions about the Research**
Prior to, during, or after your participation, you may contact the researchers below if you have any questions about this research, or feel you may have been harmed due to participation:
 
Nilavra Bhattacharya\
Phone: `<phone-number>`\
Email: `<email-address>`\
Or\
Jacek Gwizdka\
Email: `<email-address>`



**Contact Information for Questions about Your Rights as a Research Participant**
If you have questions about your rights as a research participant, or wish to obtain information, ask questions, or discuss any concerns about this study with someone other than the researcher(s), please contact the following:
 
The University of Texas at Austin\
Institutional Review Board\
Phone: `<phone-number>`\
Email: `<email-address>`
 
Please reference the study protocol number (STUDY00002136) in your communications.



**Your Consent**
By clicking the button below, you are agreeing to participate in this study. Make sure you understand what the study is about before you consent. If you have any questions about the study after you consent, you can contact the study team using the information provided above.

- By clicking this button I understand what the study is about and my questions so far have been answered. I agree to participate in this study. 



Please enter the coded username assigned to you (shared via email) .....







## Motivation {#app-qsnr-imi}

Adapted from Intrinsic Motivation Inventory (IMI) [@ryan1982control].
Items will be randomly ordered.

**Scoring directions:**
Score each response from 1 (not at all true) to 5 (very true).
Then reverse score the items marked with **(R)**.
To do that, subtract the item response from 6, and use the resulting number as the item score.
Then, calculate subscale scores by averaging across all the items on that subscale.
The subscale scores are then used in the analyses of relevant research questions.

*For each of the following statements, please indicate how true it is
for you, using the following scale:*\
*(1) not at all true --- somewhat true --- very true (5)*

### Interest/Enjoyment

1. I will enjoy taking this course very much.
1. This course will be fun to do.
1. I think this will be a boring course. **(R)**
1. This course will not hold my attention at all. **(R)**
1. I would describe this course as very interesting.
1. I think this course will be quite enjoyable.

### Perceived Competence

1. I think I will be pretty good at this course.
1. I think I will be doing pretty well at this course, compared to other students.
1. After working at this course for awhile, I will feel pretty competent.
1. I think I will be satisfied with my performance in this course.
1. I think I am pretty skilled at this course.
1. This is a course that I think would not be able to do very well. **(R)**

### Effort/Importance

1. I plan to put a lot of effort into this course.
1. I don’t think I will try very hard to do well at this course. **(R)**
1. I will try very hard on this course.
1. It is important to me to do well in this course.
1. I do not plan to put much energy into this course. **(R)**

### Value/Usefulness

1. I believe the course and the final project activities could be of some value to me.
1. I think that doing the final project activities is useful for me.
1. I think the final project is important activity to do because it can equip me with skills that are necessary for making ethical decisions in my adult and professional life.
1. I would be willing to do research on the final project topic again because it has some value to me.
1. I think doing the final project activities will help me in my adult and professional life
1. I believe doing the final project activities will be beneficial to me.
1. I think this is an important course.

### Pressure / Tension (not in `QSNR1`)

1. I do not feel nervous while doing the final project activities. **(R)**
1. I feel very tensed while doing the final project activities.
1. I am very relaxed while doing the final project activities. **(R)**
1. I feel anxious while working on the final project parts.
1. I feel pressured while doing the final project activities.

### Perceived Choice (not in `QSNR1`)

1. I believe I have some choice about doing the final project activities.
1. I feel like it is not my own choice to do the final project parts. **(R)**
1. I don't really have a choice about doing the final project tasks. **(R)**
1. I feel like I have to do the final project tasks. **(R)**
1. I do the final project activities because I have no choice. **(R)**
1. I do the final project activities because I want to.
1. I do the final project activities because I have to. **(R)**






## Self-regulation {#app-qsnr-srq}

Self-Regulation Questionnaire (SRQ) by @brown1999self.

*Please answer the following questions by selecting the option that best
describes how you are. There are no right or wrong answers. Work quickly
and don't think too long about your answers.\
\
(1) Strongly Disagree -- Disagree -- Neutral -- Agree -- Strongly Agree (5)*

1. I usually keep track of my progress toward my goals.
2. My behavior is not that different from other people's. **(R)**
3. Others tell me that I keep on with things too long. **(R)**
4. I doubt I could change even if I wanted to. **(R)**
5. I have trouble making up my mind about things. **(R)**
6. I get easily distracted from my plans. **(R)**
7. I reward myself for progress toward my goals.
8. I don't notice the effects of my actions until it's too late. **(R)**
9. My behavior is similar to that of my friends. Evaluating
10. It's hard for me to see anything helpful about changing my ways. **(R)**
11. I am able to accomplish goals I set for myself.
12. I put off making decisions. **(R)**
13. I have so many plans that it's hard for me to focus on any one of them. **(R)**
14. I change the way I do things when I see a problem with how things are going.
15. It's hard for me to notice when I've "had enough" (alcohol, food, sweets, internet, social media) **(R)**
16. I think a lot about what other people think of me.
17. I am willing to consider other ways of doing things.
18. If I wanted to change, I am confident that I could do it.
19. When it comes to deciding about a change, I feel overwhelmed by the choices. **(R)**
20. I have trouble following through with things once I've made up my mind to do something. **(R)**
21. I don't seem to learn from my mistakes. **(R)**
22. I'm usually careful not to overdo it when working, eating, drinking, or being on social media.
23. I tend to compare myself with other people.
24. I enjoy a routine, and like things to stay the same. **(R)**
25. I have sought out advice or information about changing.
26. I can come up with lots of ways to change, but it's hard for me to decide which one to use. **(R)**
27. I can stick to a plan that's working well.
28. I usually only have to make a mistake one time in order to learn from it.
29. I don't learn well from punishment. **(R)**
30. I have personal standards, and try to live up to them.
31. I am set in my ways. **(R)**
32. As soon as I see a problem or challenge, I start looking for possible solutions.
33. I have a hard time setting goals for myself. **(R)**
34. I have a lot of willpower.
35. When I'm trying to change something, I pay a lot of attention to how I'm doing.
36. I usually judge what I'm doing by the consequences of my actions.
37. I don't care if I'm different from most people. **(R)**
38. As soon as I see things aren't going right I want to do something about it.
39. There is usually more than one way to accomplish something.
40. I have trouble making plans to help me reach my goals. **(R)**
41. I am able to resist temptation.
42. I set goals for myself and keep track of my progress.
43. Most of the time I don't pay attention to what I'm doing. **(R)**
44. I try to be like people around me.
45. I tend to keep doing the same thing, even when it doesn't work. **(R)**
46. I can usually find several different possibilities when I want to change something.
47. Once I have a goal, I can usually plan how to reach it.
48. I have rules that I stick by no matter what.
49. If I make a resolution to change something, I pay a lot of attention to how I'm doing.
50. Often I don't notice what I'm doing until someone calls it to my attention. **(R)**
51. I think a lot about how I'm doing.
52. Usually I see the need to change before others do.
53. I'm good at finding different ways to get what I want.
54. I usually think before I act.
55. Little problems or distractions throw me off course. **(R)**
56. I feel bad when I don't meet my goals.
57. I learn from my mistakes.
58. I know how I want to be.
59. It bothers me when things aren't the way I want them.
60. I call in others for help when I need it.
61. Before making a decision, I consider what is likely to happen if I do one thing or another.
62. I give up quickly. **(R)**
63. I usually decide to change and hope for the best. **(R)**


**Scoring Directions:**
Score each response from 1 (strongly disagree) to 5 (strongly agree), and calculate the following seven subscale scores by
summing the items on that subscale.
Items marked **(R)** are reverse-coded (i.e. 1 = strongly agree and 5 = strongly disagree).
To do that, subtract the item response from 6, and use the resulting number as the item score.

1. *Receiving relevant information:* 1, 8, 15, 22, 29, 36, 43, 50, 57
2. *Evaluating the information and comparing it to norms:* 2, 9, 16, 23, 30, 37, 44, 51, 58
3. *Triggering change:* 3, 10, 17, 24, 31, 38, 45, 52, 59
4. *Searching for options:* 4, 11, 18, 25, 32, 39, 46, 53, 60
5. *Formulating a plan:* 5, 12, 19, 26, 33, 40, 47, 54, 61
6. *Implementing the plan:* 6, 13, 20, 27, 34, 41, 48, 55, 62
7. *Assessing the plan's effectiveness:* 7, 14, 21, 28, 35, 42, 49, 56, 63

Based on our clinical and college samples, we tentatively recommend the following ranges for interpreting SRQ total scores with the 63-item scale:

- **>= 239**: High (intact) self-regulation capacity (top quartile)
- **214 - 238**: Intermediate (moderate) self-regulation capacity (middle quartiles)
- **<= 213**: Low (impaired) self-regulation capacity (bottom quartile)




## Metacognition {#app-qsnr-mai}

Metacognitive Awareness Inventory (MAI) proposed by
@schraw1994assessing and revised by @terlecki2018call.

*Think of yourself as a **learner**. Read each statement carefully, and
rate it as it generally applies to you when you are in the role of a
learner (student, attending classes, university etc.) Please indicate
how true each reason is for you using the following scale:*

| Score | Response |
|---|---|
|1|I **NEVER** do this|
|2|I do this **infrequently**|
|3|I do this **inconsistently**|
|4|I do this **frequently**|
|5|I **ALWAYS** do this|

1. I ask myself periodically if I am meeting my goals.
1. I consider several alternatives to a problem before I answer.
1. I try to use strategies that have worked in the past.
1. I pace myself while learning in order to have enough time.
1. I understand my intellectual strengths and weaknesses.
1. I think about what I really need to learn before I begin a task.
1. I know how well I did once I finish a test.
1. I set specific goals before I begin a task.
1. I slow down when I encounter important information.
1. I know what kind of information is most important to learn.
1. I ask myself if I have considered all options when solving a problem.
1. I am good at organizing information.
1. I consciously focus my attention on important information.
1. I have a specific purpose for each strategy I use.
1. I learn best when I know something about the topic.
1. I know what the teacher expects me to learn.
1. I am good at remembering information.
1. I use different learning strategies depending on the situation.
1. I ask myself if there was an easier way to do things after I finish a task.
1. I have control over how well I learn.
1. I periodically review to help me understand important relationships.
1. I ask myself questions about the material before I begin.
1. I think of several ways to solve a problem and choose the best one.
1. I summarize what I've learned after I finish.
1. I ask others for help when I don't understand something.
1. I can motivate myself to learn when I need to.
1. I am aware of what strategies I use when I study.
1. I find myself analyzing the usefulness of strategies while I study.
1. I use my intellectual strengths to compensate for my weaknesses.
1. I focus on the meaning and significance of new information.
1. I create my own examples to make information more meaningful.
1. I am a good judge of how well I understand something.
1. I find myself using helpful learning strategies automatically.
1. I find myself pausing regularly to check my comprehension.
1. I know when each strategy I use will be most effective.
1. I ask myself how well I accomplish my goals once I'm finished.
1. I draw pictures or diagrams to help me understand while learning.
1. I ask myself if I have considered all options after I solve a problem.
1. I try to translate new information into my own words.
1. I change strategies when I fail to understand.
1. I use the organizational structure of the text to help me learn.
1. I read instructions carefully before I begin a task.
1. I ask myself if what I'm reading is related to what I already know.
1. I reevaluate my assumptions when I get confused.
1. I organize my time to best accomplish my goals.
1. I learn more when I am interested in the topic.
1. I try to break studying down into smaller steps.
1. I focus on overall meaning rather than specifics.
1. I ask myself questions about how well I am doing while I am learning something new.
1. I ask myself if I learned as much as I could have once I finish a task.
1. I stop and go back over new information that is not clear.
1. I stop and reread when I get confused.

**Scoring Directions:** Score each response from 1 (never) to 5
(always), and calculate the following subscale scores by summing the
items on that subscale.

*Knowledge about Cognition:*

1. *Declarative Knowledge:* 5, 10, 12, 16, 17, 20, 32, 46 (score out of $8\times5 = 40$)
2. *Procedural Knowledge:* 3, 14, 27, 33 (score out of $4\times5 = 20$)
3. *Conditional Knowledge:* 15, 18, 26, 29, 35 (score out of $5\times5 = 25$)

*Regulation of Cognition:*

1. *Planning:* 4, 6, 8, 22, 23, 42, 45 (score out of $7\times5 = 35$)
2. *Information Management Strategies:* 9, 13, 30, 31, 37, 39, 41, 43, 47, 48 (score out of $10\times5 = 50$)
3. *Comprehension Monitoring:* 1, 2, 11, 21, 28, 34, 49 (score out of $7\times5 = 35$)
4. *Debugging Strategies:* 25, 40, 44, 51, 52 (score out of $5\times5 = 25$)
5. *Evaluation:* 7, 19, 24, 36, 38, 50 (score out of $6\times5 = 30$)















<!-- 
## Search and IT Proficiency {#app-search-it-proficiency}

1. Which device(s) and browser(s) do you normally use to surf the internet?

| Choice | Chrome (1) | Safari (2) | Firefox (3) | Edge (4) | Opera (5) | Other (6) | None (7) |
| --- | --- |--- |--- |--- |--- |--- |--- |
|Desktop | | | | | | | |
|Laptop | | | | | | | |
|Tablet | | | | | | | |
|Smartphone | | | | | | | |
|||||||||

2. How comfortable are you with using Mozilla Firefox to search information on the internet?

    1. I do not know how to use Mozilla Firefox.
    2. I have never used Mozilla Firefox.
    3. I feel very uncomfortable to use Mozilla Firefox.
    4. I feel uncomfortable to use Mozilla Firefox.
    5. I feel neither comfortable nor uncomfortable to use Mozilla Firefox.
    6. I feel comfortable to use Mozilla Firefox.
    7. I feel very comfortable to use Mozilla Firefox.
    8. Other: ......

3. Which search engines do you normally use?
    1. Google
    1. Bing
    1. Baidu
    1. Yahoo!
    1. Yandex
    1. DuckDuckGo
    1. Other:

The following items are adapted from the **Digital Health Literacy Instrument (DHLI)** by @van2017development.

*On a scale of 1 to 5 ...\
(1) Very difficult / Very seldom -- Difficult / Seldom -- Neutral -- Easy / Often -- Very easy / Very often (5)*

*How easy or difficult is it for you to...*

4. Use the keyboard of a computer (e.g., to type words)?
1. Use the mouse (e.g., to put the cursor in the right field or to click)?
1. Use the buttons or links and hyperlinks on websites?

*When you search the Internet for information, how easy or difficult is it for you to ...*

7. Make a choice from all the information you find?
1. Use the proper words or search query to find the information you are looking for
1. Find the exact information you are looking for?
1. Decide whether the information is reliable or not?
1. Decide whether the information is written with commercial interests (e.g., by people trying to sell a product)?
1. Check different websites to see whether they provide the same information?
1. Decide if the information you found is applicable to your situation?
1. Apply the information you found in your daily life?
1. Use the information you found to make decisions about your life

*When you search the Internet for information, how often does it happen that...*

16. You lose track of where you are on a website or the Internet?
1. You do not know how to return to a previous page?
1. You click on something and get to see something different than you expected?

The following items are adapted from the **Search Self-Efficacy Scale (SSE)** by @brennan2016factor.

*On a scale of 1 to 5, how confident are you that you can ...\
(1) Not at all confident -- Neither confident nor unconfident -- Totally confident (5)*

19. Identify the major requirements of the search from the initial statement of the topic.
1. Correctly develop search queries to reflect my requirements.
1. Use special syntax in advanced searching (e.g., AND, OR, NOT).
1. Evaluate the resulting list to monitor the success of my approach.
1. Develop a search query which will retrieve a large number of appropriate articles.
1. Find an adequate number of articles.
1. Find articles similar in quality to those obtained by a professional searcher.
1. Devise a query which will result in a very small percentage of irrelevant items on my list.
1. Efficiently structure my time to complete the task.
1. Develop a focused search query that will retrieve a small number of appropriate articles.
1. Distinguish between relevant and irrelevant articles.
1. Complete the search competently and effectively.
1. Complete the individual steps of the search with little difficulty.
1. Structure my time effectively so that I will finish the search in the allocated time.

## Course Load and Other Engagements {#app-course-load}

1. How many total weekly hours of coursework are you registered for this semester?
2. How many weekly hours do you anticipate putting in for studying this course?
3. What are your other time commitments, as hours per week? (enter 0 if not applicable)
    - jobs
    - extra-curriculars
    - other
4. Do you hold a position of responsibility (officer / committee member) in any (student) organisation? Yes / No

## Note-taking Strategies {#app-note-taking-strategies}

Adapted from *Listening and Note Taking Survey* by
[@note-taking-survey-penn-state], and *Note Taking Strategies Inventory*
by [@note-taking-strategies-umass].

*For each question, choose the response that best describes your actions
(not the one that describes what you think you should be doing). There
are no right or wrong answers. In general (not specifically for this
course)*

1. I take notes using (check all that apply)
    - Paper and Pen / Pencil
    - Laptop / Desktop
    - Tablet with Keyboard
    - Tablet with Stylus / Digital Pen
2. When taking notes on the laptop, I minimize distractions by:

---

*On a scale of 1 to 5 ...\
(1) Never -- Rarely -- Sometimes -- Often -- Always (5)*

3. I read my assignments before I go to lecture.
1. I find lectures interesting and/or challenging.
1. My lecture notes are well organized.
1. I recognize main ideas in lectures.
1. I recognize supporting details of main ideas.
1. I recognize patterns in lectures, e.g., cause-effect, concept-example.
1. My lecture notes are complete.
1. I recognize relationships between lecture and readings.
1. I integrate my lecture notes with my reading notes.
1. I summarize my notes, both lecture and reading, in my own words.
1. I review my notes immediately after class.
1. I conduct weekly reviews of my notes.
1. I edit my notes within 24 hours after class.
1. I take notes
1. I put dates on my notes
1. I makes notes in the margins of the text when I read (on paper / digital medium, e.g. iPad and Apple Pencil)
1. I pause periodically while reviewing notes to summarize or paraphrase the information.
1. I use diagrams in my notes
1. I use different colours when writing notes
1. I create outlines, concept maps or organizational charts of how ideas fit together.
1. I write down questions I want to ask the instructor
1. I reorganize and fill in notes I took in class
1. I put things in my own words
1. I rewrite my notes
1. I use abbreviations in my notes
1. I write out my own descriptions of the main concepts
1. I keep track of things I do not understand and note when they finally become clear and what made that happen
1. I understand my notes
1. I refer back to my notes

---

32. How do you organise your notes? ......
33. Have you ever wished that you had written better notes? Why?
    - Yes: ......
    - No: ......
34. How long do you store your notes for?
    1. Till the end of the semester
    1. End of academic year
    1. End of college
    1. Lifelong
    1. Other: ......

35. How do you search for a bit of information in your notes? 
-->
